# Generated by Django 4.2.1 on 2023-05-07 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Carac',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('municipios', models.TextField()),
                ('areas', models.TextField()),
                ('barrio_vereda', models.TextField()),
                ('punt_sisb', models.IntegerField()),
                ('nivel_sisb', models.IntegerField()),
                ('estrato', models.IntegerField()),
                ('tipo_vivi', models.IntegerField()),
                ('tenencia', models.IntegerField()),
                ('sanitario', models.IntegerField()),
                ('alumbrado', models.IntegerField()),
                ('hacinami', models.TextField()),
                ('gatos_cant', models.IntegerField()),
                ('gatos_vacu', models.IntegerField()),
                ('perros_can', models.IntegerField()),
                ('perros_vac', models.IntegerField()),
                ('equino_can', models.IntegerField()),
                ('equino_vac', models.IntegerField()),
                ('aves', models.IntegerField()),
                ('porcinos', models.IntegerField()),
                ('fuent_agua', models.IntegerField()),
                ('acueducto', models.IntegerField()),
                ('basuras', models.IntegerField()),
                ('reci_basur', models.TextField()),
                ('iluminacio', models.TextField()),
                ('ventilacio', models.TextField()),
                ('reservorio', models.TextField()),
                ('anjeos', models.TextField()),
                ('aseo', models.TextField()),
                ('orden', models.TextField()),
                ('piso_habi', models.IntegerField()),
                ('piso_cocin', models.IntegerField()),
                ('piso_baño', models.IntegerField()),
                ('pare_habit', models.IntegerField()),
                ('pare_cocina', models.IntegerField()),
                ('pare_baño', models.IntegerField()),
            ],
        ),
    ]
