# Generated by Django 4.2.1 on 2023-05-07 19:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('proyecto_paipa_data', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='carac',
            old_name='pare_baño',
            new_name='pare_bano',
        ),
        migrations.RenameField(
            model_name='carac',
            old_name='pare_cocina',
            new_name='pare_cocin',
        ),
        migrations.RenameField(
            model_name='carac',
            old_name='piso_baño',
            new_name='piso_bano',
        ),
        migrations.RenameField(
            model_name='carac',
            old_name='piso_habi',
            new_name='piso_habit',
        ),
    ]
